### ISSUE TITLE
R Ladies BA Presentation

### ISSUE THREAD

**Issue by paocorrales** [raynamharris/FMR1CA1rnaseq#1]
Hi Rayna, 

I'm Pao from R Ladies Buenos Aires. Laura asked me to give you some feedback about your presentation. It's very interesting and I can't wait to hear it! 
Maybe I can help you with some typos in spanish. I'll make some pull request in the .tex file and then you decide.

See you on Tuesday

**Comment by raynamharris** [comment]
Thanks! I looked through all the changes and they are excellent! Thanks for helping me improve the talk!
